spring.application.name=Digital-Banking-Eureka

server.port= 9095

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
git #eureka.server.enableSelfPreservation=false