// Import necessary Angular core modules and decorators
import { Component, EventEmitter, Input, Output, OnChanges, OnInit } from '@angular/core';
// Import Angular forms modules and services for form handling and validation
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators, FormControl } from '@angular/forms';
// Import custom services and interfaces for account handling
import { AccountService, Account } from '../../services/account.service';
// Import Angular common module
import { CommonModule } from '@angular/common';
// Import Angular Material modules for form field, input, and autocomplete components
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
// Import RxJS Observable and operators for reactive programming
import { Observable } from 'rxjs';
import { startWith, map } from 'rxjs/operators';
// Import custom service for customer handling
import { CustomerService } from '../../services/customer.service';

@Component({
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatAutocompleteModule
  ],
  selector: 'app-account-form',
  templateUrl: './account-form.component.html',
  styleUrls: ['./account-form.component.css']
})
export class AccountFormComponent implements OnInit, OnChanges {
  @Input() account: Account | null = null;
  @Output() formSubmit = new EventEmitter<void>();

  accountForm: FormGroup;
  customerControl: FormControl = new FormControl('', Validators.required);
  customers: any[] = [];
  filteredCustomers!: Observable<any[]>;

  constructor(
    private fb: FormBuilder,
    private accountService: AccountService,
    private customerService: CustomerService
  ) {
    // Initialize form; note that accountNumber is included but will be omitted in new account creation
    this.accountForm = this.fb.group({
      accountNumber: ['', [Validators.minLength(8)]],
      customer: [null, Validators.required],
      accountType: ['', Validators.required],
      balance: [0, [Validators.required, Validators.min(0)]],
      status: ['active']
    });
  }

  ngOnInit(): void {
    // Load customers for the autocomplete
    this.customerService.getCustomers().subscribe(data => {
      this.customers = data;
      this.filteredCustomers = this.customerControl.valueChanges.pipe(
        startWith(''),
        map(value => typeof value === 'string' ? value : value?.name),
        map(name => name ? this._filterCustomers(name) : this.customers.slice())
      );
    });
  }

  ngOnChanges(): void {
    if (this.account) {
      // Patch form values when editing an existing account
      this.accountForm.patchValue(this.account);
    }
  }

  private _filterCustomers(name: string): any[] {
    const filterValue = name.toLowerCase();
    return this.customers.filter(customer =>
      customer.name.toLowerCase().includes(filterValue)
    );
  }

  // Display function for autocomplete
  displayCustomer(customer: any): string {
    return customer && customer.name ? customer.name : '';
  }

  // When a customer is selected, update the form control
  onCustomerSelected(customer: any): void {
    this.accountForm.patchValue({ customer });
  }

  submitForm(): void {
    if (this.accountForm.invalid) return;

    // Get form data
    const accountData = { ...this.accountForm.value };

    // For new accounts, remove accountNumber since it will be auto-generated by the backend
    if (!this.account) {
      delete accountData.accountNumber;
    }

    if (this.account) {
      this.accountService.updateAccount(this.account.id, accountData).subscribe(() => {
        this.formSubmit.emit();
      });
    } else {
      this.accountService.createAccount(accountData).subscribe(() => {
        this.formSubmit.emit();
      });
    }
  }
}
